In [2]:
#numpy is a python library ,used to work with arrays
#created in 2005
#these functions can be used in linear algebra and matrices
#free 
#numpy stands for numerical python
#in python we have list's concept but these lists are slow to process than numpy introduce arrays concept
#these arrays are very fast to access because the data is distributed in continuous memory location unlike lists

In [4]:
#we pass list
import numpy as np
arr=np.array([10,20,30])
arr

array([10, 20, 30])

In [5]:
np.__version__

'1.21.5'

In [6]:
type(arr)

numpy.ndarray

In [17]:
#we pass tuple
import numpy as np
arr=np.array((10,20,30))
arr

array([10, 20, 30])

In [18]:
#0-d array contains single element
a=np.array(10)
a

array(10)

In [19]:
#1-d -collection of 0-d arrays
import numpy as np
a1=np.array([10,20,30])
a1

array([10, 20, 30])

In [20]:
#2-d a[3][3]
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
#3-d
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
#ndim attributes says how many dimensions present in a array
print(a.ndim)
print(a1.ndim)
print(b.ndim)
print(c.ndim)

0
1
2
3


In [28]:
#array indexing-means access elements with the help of index
#access 1-d array elements
print(arr)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[0]+arr[2])

[10 20 30]
10
20
30
40


In [31]:
#access 2-d array elements
#r-r0,r1,r2 c-c0,c1,c2
print(b)
print(b[1,2])
print(b[2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
7


In [34]:
##access 3-d array elements
print(c)
print(c[0,1,0])
print(c[1,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
4
11


In [38]:
#use negative index for accessing from end
print(b)
print(b[2,-2])
print(b[1,-3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
4


In [48]:
arr1=np.array([1,2,4,6,9,0,3,5])
print(arr1)
print(arr1[1:5])
print(arr1[1:])
print(arr1[:5])
print(arr1[:-1])
print(arr1[-8:])
print(arr1[-6:-1])
print(arr1[0::2])
print(arr1[::2])

[1 2 4 6 9 0 3 5]
[2 4 6 9]
[2 4 6 9 0 3 5]
[1 2 4 6 9]
[1 2 4 6 9 0 3]
[1 2 4 6 9 0 3 5]
[4 6 9 0 3]
[1 4 9 3]
[1 4 9 3]


In [50]:
#returns datatype of array
print(arr1.dtype)

int32


In [52]:
#define datatype
arr=np.array([1,2,3],dtype='S')
print(arr.dtype)

|S1
