In [10]:
import numpy as np
arr=np.array([1,2,3],dtype='S')
print(arr.dtype)

|S1


In [11]:
#astype can be used to convert datatype
arr=arr.astype(int)
print(arr.dtype)

int32


In [12]:
#copy can own the data ,if we made changes than original array cannot affect unlike view
print(arr)
x=arr.copy()
y=arr.view()
arr[1]=5
print(x)
print(y)

[1 2 3]
[1 2 3]
[1 5 3]


In [14]:
#base attribute can used to check whether own the data or not ,if owns print none else return object
print(x.base)
print(y.base)

None
[1 5 3]


In [17]:
#shape can be used to describe dimensions
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [19]:
#reshape can be used to change dimensions like 1-d to 2-d
print(arr1)
print(arr1.reshape(1,6))

[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [24]:
#2-d to 3-d
print(arr1.reshape(2,3,1))

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [25]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [26]:
for i in arr1:
    print(i)

[1 2 3]
[4 5 6]


In [27]:
for i in arr1:
    for j in i:
        print(j)

1
2
3
4
5
6


In [2]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [3]:
#nditer function can be used for iteration for high dimensions
for i in np.nditer(arr):
    print(i)

10
20
30
40
50
60


In [6]:
#join operation using concatenate function
#this function can be used to display all arrays content into a single array
#here we are using axis=1  for rows wise display  and axis=0 for column
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [10]:
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [15]:
#stack function can also used for join operation
print(arr1)
print(arr2)
arr=np.stack((arr1,arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
#stack function can also used for join operation
print(arr1)
print(arr2)
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [20]:
#splitting is reverse operation to join,it can split array into multiple arrays
arr=np.array([1,2,3,4])
print(np.array_split(arr,2))
print(np.array_split(arr,3))
print(np.array_split(arr,4))

[array([1, 2]), array([3, 4])]
[array([1, 2]), array([3]), array([4])]
[array([1]), array([2]), array([3]), array([4])]


In [24]:
#where can be used to find an element in array
a=np.array([1,8,0,2,6])
print(np.where(a==2))
print(np.where(a==7))

(array([3], dtype=int64),)
(array([], dtype=int64),)


In [28]:
#we can also use search sorted method ,but the array should be in sorted order
print(arr)
print(np.searchsorted(arr,2))
print(np.searchsorted(arr,10))

[1 2 3 4]
1
4


In [29]:
#sort function can be used sort an array
arr=np.array([[12,1],[3,7],[0,-4]])
print(np.sort(arr))

[[ 1 12]
 [ 3  7]
 [-4  0]]


In [30]:
arr1=np.array([1,0,4,-5,-2])
print(np.sort(arr1))

[-5 -2  0  1  4]


In [31]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [32]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [33]:
np.random.rand(2,3)

array([[0.48527182, 0.85077773, 0.46150544],
       [0.02289725, 0.01647792, 0.14533334]])

In [34]:
np.random.rand(2)

array([0.16335683, 0.31154318])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.full([2,4],6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [48]:
print(arr1)
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.median(a))
print(np.mean(a))
print(np.std(a))

[ 1  0  4 -5 -2]
0
8
17
2.0
3.4
3.072458299147443


In [49]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.square(arr1,arr2))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [50]:
#array_equal function can be used for comparisions
print(np.array_equal(arr1,arr2))

False


In [51]:
print(arr1)
print(np.append(arr1,4))

[1 2 3]
[1 2 3 4]
